# Generated by Django 4.2.1 on 2024-03-16 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_name', models.CharField(max_length=30, verbose_name='Заголовок')),
                ('contents', models.TextField(verbose_name='Содержимое')),
                ('publication_date', models.DateField(verbose_name='Дата публикации')),
                ('views_count', models.IntegerField(default=0, verbose_name='Количество просмотров')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'блог',
                'verbose_name_plural': 'блоги',
                'ordering': ('article_name',),
            },
        ),
    ]
