# Generated by Django 4.2.1 on 2024-03-16 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='contents',
            field=models.TextField(verbose_name='Содержимое статьи'),
        ),
    ]
