# Generated by Django 4.2.1 on 2024-03-17 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_image_alter_blog_contents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='Фото'),
        ),
    ]
