# Generated by Django 4.2.1 on 2024-03-11 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_email', models.CharField(max_length=150, unique=True, verbose_name='Контактный email')),
                ('client_name', models.CharField(max_length=150, verbose_name='ФИО')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'клиент',
                'verbose_name_plural': 'клиенты',
            },
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_try', models.DateTimeField(verbose_name='Дата и время последней попытки')),
                ('status_try', models.CharField(max_length=20, verbose_name='Статус попытки')),
                ('server_answer', models.TextField(blank=True, default='', null=True, verbose_name='Ответ сервера')),
                ('send_name', models.CharField(default=None, max_length=200, verbose_name='Наименование рассылки')),
                ('send_email', models.EmailField(blank=True, max_length=150, null=True, verbose_name='Почта отправки')),
            ],
            options={
                'verbose_name': 'лог',
                'verbose_name_plural': 'логи',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Тема письма')),
                ('text', models.TextField(verbose_name='Тело письма')),
            ],
            options={
                'verbose_name': 'сообщение',
                'verbose_name_plural': 'сообщения',
            },
        ),
        migrations.CreateModel(
            name='MailingOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailing_name', models.CharField(default=None, max_length=200, verbose_name='Наименование рассылки')),
                ('mailing_start', models.DateTimeField(default=None, verbose_name='Время начала рассылки')),
                ('mailing_finish', models.DateTimeField(default=None, verbose_name='Время окончания рассылки')),
                ('next_try', models.DateTimeField(blank=True, null=True, verbose_name='Следующая попытка')),
                ('mailing_period', models.CharField(choices=[('Ежедневно', 'Ежедневно'), ('Еженедельно', 'Еженедельно'), ('Ежемесячно', 'Ежемесячно')], default='', max_length=20, verbose_name='Периодичность')),
                ('mailing_status', models.CharField(choices=[('Создана', 'Создана'), ('Запущена', 'Запущена'), ('Завершена', 'Завершена')], default='Создана', max_length=20, verbose_name='Статус рассылки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
                ('client_email', models.ManyToManyField(to='service.client', verbose_name='контактный email')),
                ('mail_title', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='service.message', verbose_name='Тема рассылки')),
            ],
            options={
                'verbose_name': 'настройка',
                'verbose_name_plural': 'настройки',
            },
        ),
    ]
